// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeihnnY-4_Lh1Jg8WrmGdAjO2tRzoqTbE',
    appId: '1:720877349296:web:45b8e1cfdacc0781914e75',
    messagingSenderId: '720877349296',
    projectId: 'expense-tracker-c66de',
    authDomain: 'expense-tracker-c66de.firebaseapp.com',
    storageBucket: 'expense-tracker-c66de.firebasestorage.app',
    measurementId: 'G-F7BGQC78S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx81OX2JEQ35zzH3ZLc05S70Q6IhgFoDo',
    appId: '1:720877349296:android:65d41cd374b3f46c914e75',
    messagingSenderId: '720877349296',
    projectId: 'expense-tracker-c66de',
    storageBucket: 'expense-tracker-c66de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuoRonKD1IKAOCmYeRL9obgIDt9u0Yw24',
    appId: '1:720877349296:ios:188392cd4fd32067914e75',
    messagingSenderId: '720877349296',
    projectId: 'expense-tracker-c66de',
    storageBucket: 'expense-tracker-c66de.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuoRonKD1IKAOCmYeRL9obgIDt9u0Yw24',
    appId: '1:720877349296:ios:188392cd4fd32067914e75',
    messagingSenderId: '720877349296',
    projectId: 'expense-tracker-c66de',
    storageBucket: 'expense-tracker-c66de.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeihnnY-4_Lh1Jg8WrmGdAjO2tRzoqTbE',
    appId: '1:720877349296:web:7c9b9c4ecec1bd26914e75',
    messagingSenderId: '720877349296',
    projectId: 'expense-tracker-c66de',
    authDomain: 'expense-tracker-c66de.firebaseapp.com',
    storageBucket: 'expense-tracker-c66de.firebasestorage.app',
    measurementId: 'G-9H3X30YRVZ',
  );
}
